import { PT_Sans} from "next/font/google";
import "./globals.css";
import "./styles/nubesInicio.css";
const ptSans = PT_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={ptSans.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
